-- AlterTable
ALTER TABLE "Order" ADD COLUMN "delay" INTEGER;
ALTER TABLE "Order" ADD COLUMN "expiry" DATETIME;
ALTER TABLE "Order" ADD COLUMN "maxPerPost" INTEGER;
ALTER TABLE "Order" ADD COLUMN "minPerPost" INTEGER;
ALTER TABLE "Order" ADD COLUMN "posts" INTEGER;
